/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import db.Authorisation;
import javax.swing.JOptionPane;

/**
 *
 * @author aamir
 */
public class Admin_Home extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Home
     */
    public Admin_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vProfile = new javax.swing.JButton();
        vMobile = new javax.swing.JButton();
        UProfile = new javax.swing.JButton();
        DProfile = new javax.swing.JButton();
        UMobile = new javax.swing.JButton();
        DMobile = new javax.swing.JButton();
        vPurchase = new javax.swing.JButton();
        dPurchase = new javax.swing.JButton();
        vFeedback = new javax.swing.JButton();
        vLog = new javax.swing.JButton();
        DLog = new javax.swing.JButton();
        DALog = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        Dfeed = new javax.swing.JButton();
        DAFeed = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        vSale = new javax.swing.JButton();
        DSale = new javax.swing.JButton();
        SIGNUP = new javax.swing.JButton();
        mobile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 3, 36)); // NOI18N
        jLabel1.setText("WELCOME ADMIN");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel2.setText("Profile");

        jLabel3.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel3.setText("Mobile");

        jLabel4.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel4.setText("Purchase Report");

        jLabel5.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel5.setText("Feedback");

        jLabel6.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel6.setText("LogIn Details");

        vProfile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vProfile.setText("VIEW");
        vProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vProfileActionPerformed(evt);
            }
        });

        vMobile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vMobile.setText("VIEW");
        vMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vMobileActionPerformed(evt);
            }
        });

        UProfile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UProfile.setText("UPDATE");
        UProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UProfileActionPerformed(evt);
            }
        });

        DProfile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DProfile.setText("DELETE");
        DProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DProfileActionPerformed(evt);
            }
        });

        UMobile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UMobile.setText("UPDATE");
        UMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UMobileActionPerformed(evt);
            }
        });

        DMobile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DMobile.setText("DELETE");
        DMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMobileActionPerformed(evt);
            }
        });

        vPurchase.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vPurchase.setText("VIEW");
        vPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vPurchaseActionPerformed(evt);
            }
        });

        dPurchase.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dPurchase.setText("DELETE");
        dPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dPurchaseActionPerformed(evt);
            }
        });

        vFeedback.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vFeedback.setText("VIEW");
        vFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vFeedbackActionPerformed(evt);
            }
        });

        vLog.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vLog.setText("VIEW");
        vLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vLogActionPerformed(evt);
            }
        });

        DLog.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DLog.setText("DELETE");
        DLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DLogActionPerformed(evt);
            }
        });

        DALog.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DALog.setText("DELETE ALL");
        DALog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DALogActionPerformed(evt);
            }
        });

        logOut.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logOut.setText("LOGOUT");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        Dfeed.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Dfeed.setText("DELETE");
        Dfeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DfeedActionPerformed(evt);
            }
        });

        DAFeed.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DAFeed.setText("DELETE ALL");
        DAFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAFeedActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel7.setText("Sale's Report");

        vSale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vSale.setText("VIEW");
        vSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vSaleActionPerformed(evt);
            }
        });

        DSale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DSale.setText("DELETE");
        DSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSaleActionPerformed(evt);
            }
        });

        SIGNUP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SIGNUP.setText("ADD USER");
        SIGNUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGNUPActionPerformed(evt);
            }
        });

        mobile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mobile.setText("ADD MOBILE");
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(vFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(Dfeed, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(DAFeed))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vLog, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(DLog, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(DALog)))
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vSale, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DSale, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SIGNUP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vProfile)
                    .addComponent(UProfile)
                    .addComponent(DProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SIGNUP)
                .addGap(13, 13, 13)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vMobile)
                    .addComponent(UMobile)
                    .addComponent(DMobile))
                .addGap(7, 7, 7)
                .addComponent(mobile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vSale)
                    .addComponent(DSale))
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vPurchase)
                    .addComponent(dPurchase))
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vFeedback)
                    .addComponent(Dfeed)
                    .addComponent(DAFeed))
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vLog)
                    .addComponent(DLog)
                    .addComponent(DALog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vLogActionPerformed
        View_LoginHistory l=new View_LoginHistory();
        l.setVisible(true);
    }//GEN-LAST:event_vLogActionPerformed

    private void vFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vFeedbackActionPerformed
        View_Feedback f=new View_Feedback();
        f.setVisible(true);
    }//GEN-LAST:event_vFeedbackActionPerformed

    private void DSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSaleActionPerformed
        DeleteF d=new DeleteF("sales_report");
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_DSaleActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        Authorisation.status="denied";
        Authorisation.role=null;
        LogIn l=new LogIn();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutActionPerformed

    private void vProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vProfileActionPerformed
        View_Profile p=new View_Profile();
        p.setVisible(true);
    }//GEN-LAST:event_vProfileActionPerformed

    private void vMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vMobileActionPerformed
        View_Mobiles m=new View_Mobiles();
        m.setVisible(true);
    }//GEN-LAST:event_vMobileActionPerformed

    private void vSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vSaleActionPerformed
        View_SaleReport s=new View_SaleReport();
        s.setVisible(true);
    }//GEN-LAST:event_vSaleActionPerformed

    private void vPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vPurchaseActionPerformed
        View_PurchaseReport p=new View_PurchaseReport();
        p.setVisible(true);
    }//GEN-LAST:event_vPurchaseActionPerformed

    private void DAFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAFeedActionPerformed
        if(db.DeleteAll.delete("feedback")){
            JOptionPane.showMessageDialog(this, "All records deleted");
        }else{
            JOptionPane.showMessageDialog(this, "unable to delete records");
        }
    }//GEN-LAST:event_DAFeedActionPerformed

    private void DALogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DALogActionPerformed
        if(db.DeleteAll.delete("login_history")){
            JOptionPane.showMessageDialog(this, "All records deleted");
        }else{
            JOptionPane.showMessageDialog(this, "unable to delete records");
        }
    }//GEN-LAST:event_DALogActionPerformed

    private void DProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DProfileActionPerformed
        DeleteF d=new DeleteF("profiles");
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_DProfileActionPerformed

    private void DMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMobileActionPerformed
        DeleteF d=new DeleteF("mobile");
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_DMobileActionPerformed

    private void dPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dPurchaseActionPerformed
        DeleteF d=new DeleteF("purchase_report");
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_dPurchaseActionPerformed

    private void DfeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DfeedActionPerformed
        DeleteF d=new DeleteF("feedback");
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_DfeedActionPerformed

    private void DLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DLogActionPerformed
        DeleteF d=new DeleteF("login_history");
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_DLogActionPerformed

    private void UProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UProfileActionPerformed
        UpdateC u=new UpdateC("profiles");
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_UProfileActionPerformed

    private void UMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UMobileActionPerformed
        UpdateC u=new UpdateC("mobile");
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_UMobileActionPerformed

    private void SIGNUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGNUPActionPerformed
        SignUp s=new SignUp();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_SIGNUPActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        Add_Mobile s=new Add_Mobile();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_mobileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DAFeed;
    private javax.swing.JButton DALog;
    private javax.swing.JButton DLog;
    private javax.swing.JButton DMobile;
    private javax.swing.JButton DProfile;
    private javax.swing.JButton DSale;
    private javax.swing.JButton Dfeed;
    private javax.swing.JButton SIGNUP;
    private javax.swing.JButton UMobile;
    private javax.swing.JButton UProfile;
    private javax.swing.JButton dPurchase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton logOut;
    private javax.swing.JButton mobile;
    private javax.swing.JButton vFeedback;
    private javax.swing.JButton vLog;
    private javax.swing.JButton vMobile;
    private javax.swing.JButton vProfile;
    private javax.swing.JButton vPurchase;
    private javax.swing.JButton vSale;
    // End of variables declaration//GEN-END:variables
}
